### ISSUE TITLE
Definir el título del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#1]

**Comment by InfernalRexPain** [comment]
Procesos Geológicos Planetarios
![Logotipo_Proyecto](https://user-images.githubusercontent.com/66383574/85207053-cfb49b00-b2eb-11ea-9f84-77ce33b954a6.png)

**Comment by JohnFlorez25** [comment]
@InfernalRexPain efectivamente el título cumple con el objetivo de lo que vamos a realizar en el proyecto, pero recuerda que esto debe estar en la WIKI
