### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#2]

**Comment by InfernalRexPain** [comment]
![Verde Azul Triangular Espinazo Diagrama Gráfico](https://user-images.githubusercontent.com/66383574/85206679-4ac88200-b2e9-11ea-88fd-1eee8f3c183f.png)

**Comment by JohnFlorez25** [comment]
El diagrama de espina de pescado debe estar orientado al problema sobre el cual va a ser objetivo plantear la solución de una plataforma móvil donde las personas aprendan sobre los procesos geológicos

**Comment by JohnFlorez25** [comment]
A la fecha no se evidencian cambios y actualizaciones en el diagrama de espina de pescado

**Comment by InfernalRexPain** [comment]
@JohnFlorez25 Ya realicé la actualización que me sugeriste del diagrama de espina de pescado
