### ISSUE TITLE
Declarar la situación del Problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#3]

**Comment by InfernalRexPain** [comment]
[Declaración de la situación Media Técnica.docx](https://github.com/JohnFlorez25/equipo6_sa_ppi2020/files/4808243/Declaracion.de.la.situacion.Media.Tecnica.docx)

**Comment by JohnFlorez25** [comment]
La declaración de la situación del problema debe ser puntual empezando por el problema que se identificó, que causa este problema y en que tiene efecto, remitirse al ejemplo de la semana 2 de I.R - Análisis del Problema

**Comment by InfernalRexPain** [comment]
@JohnFlorez25 Ya lo terminé, lo puedes cerrar :)

**Comment by JohnFlorez25** [comment]
@InfernalRexPain al igual como te había dejado el comentario anterior 

> : La declaración de la situación del problema debe ser puntual empezando por el problema que se identificó, que causa este problema y en que tiene efecto, remitirse al ejemplo de la semana 2 de I.R - Análisis del Problema.

Aunque tienes información valiosa se debe ser concreto con lo que se va a exponer desde este punto en el pitch del proyecto, es valioso el tiempo  y debes ser muy claro sobre el problema que vas a abordar
