### ISSUE TITLE
Describir cada uno de los interesados

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#4]

**Comment by InfernalRexPain** [comment]
[Interesados en el sistema Arley Quintero 11°2.docx](https://github.com/JohnFlorez25/equipo6_sa_ppi2020/files/4808244/Interesados.en.el.sistema.Arley.Quintero.11.2.docx)

**Comment by InfernalRexPain** [comment]
@JohnFlorez25 Ya terminé este punto, ahora si lo puedes cerrar :)
