### ISSUE TITLE
Construir el tablero de visión del producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#5]

**Comment by InfernalRexPain** [comment]
![Tablero_Visión del_Producto](https://user-images.githubusercontent.com/66383574/86819165-e3326680-c04c-11ea-95b3-62792df70fbd.png)

**Comment by InfernalRexPain** [comment]
@JohnFlorez25 Ya lo terminé, lo puedes cerrar :)

**Comment by JohnFlorez25** [comment]
@InfernalRexPain la descripción de la visión del producto debe cumplir con la regla que está estipulada en la guía de   "Análisis del Problema" que viste en la materia de Interpretación de Requerimientos, de esta forma no divagas en temas distintos a la información puntual y clara que debes mencionar al realizar la descripción de la visión del producto
