### ISSUE TITLE
Validar con 5 usuarios la viabilidad del sistema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#6]

**Comment by InfernalRexPain** [comment]
![IMG-20200616-WA0007](https://user-images.githubusercontent.com/66383574/85206633-0a690400-b2e9-11ea-8f91-ccdfdcd7ceb2.jpg)

**Comment by InfernalRexPain** [comment]
@JohnFlorez25 Ya está finalizado, lo puedes cerrar :)

**Comment by JohnFlorez25** [comment]
@InfernalRexPain Debes mejorar los textos del cuadro, usa fuentes normales ya que queda muy saturada la información y debemos diligenciar los distintos procesos de una forma muy profesional

**Comment by InfernalRexPain** [comment]
![Validación](https://user-images.githubusercontent.com/66383574/90055903-adb01700-dca3-11ea-8b76-16b729a87fa9.png)
