### ISSUE TITLE
- [ ] Hacer mapa de Historia de Usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sa_ppi2020#9]

**Comment by InfernalRexPain** [comment]
[HISTORIA DE USUARIOS Y CRITERIOS DE ACEPTACION,PROCESOS GEOLOGICOS.docx](https://github.com/JohnFlorez25/equipo6_sa_ppi2020/files/5065115/HISTORIA.DE.USUARIOS.Y.CRITERIOS.DE.ACEPTACION.PROCESOS.GEOLOGICOS.docx)

**Comment by InfernalRexPain** [comment]
![fx](https://user-images.githubusercontent.com/66383574/90092894-d958ee80-dcef-11ea-8cca-da34123cabb9.png)

**Comment by InfernalRexPain** [comment]
![IMG-20200812-WA0014](https://user-images.githubusercontent.com/66383574/90093460-4620b880-dcf1-11ea-98be-772a3cce1c6f.jpg)
